### PR TITLE
Fix envs

### PR DESCRIPTION
**Pull request by raymondjacobson**
Currently stage shows prod data.

This works, but it's kinda ugly to do

### CODE REVIEW

**Review by rickyrombo — APPROVED** [review]
Who you calling ugly? 😂 

But actually mimicking this might make it a bit cleaner: 
https://github.com/AudiusProject/audius-client/blob/0f7e352c1fa5a6a8b7e7b4e57c7dfea54d6a6ce1/packages/web/src/services/audius-sdk/audiusSdk.ts#L39-L44

**Comment by raymondjacobson** [comment]
> Who you calling ugly? 😂
> 
> But actually mimicking this might make it a bit cleaner: https://github.com/AudiusProject/audius-client/blob/0f7e352c1fa5a6a8b7e7b4e57c7dfea54d6a6ce1/packages/web/src/services/audius-sdk/audiusSdk.ts#L39-L44

Yes that's better!

**Comment by raymondjacobson** [comment]
> > Who you calling ugly? 😂
> > But actually mimicking this might make it a bit cleaner: https://github.com/AudiusProject/audius-client/blob/0f7e352c1fa5a6a8b7e7b4e57c7dfea54d6a6ce1/packages/web/src/services/audius-sdk/audiusSdk.ts#L39-L44
> 
> Yes that's better!

We should document/show off this example

**Comment by raymondjacobson** [comment]
@rickyrombo thank u

**Pull request merged**
